
class SFF:
    #From SFF-8024 v4.4 - table 4-4 
    sff_extended_specification_compliance_codes = {0x00: 'unspecified',
                                                   0x01: '100G AOC or 25GAUI C2M',
                                                   0x02: '100GBase-SR4 or 25GBase-SR',
                                                   0x03: '100GBase-LR4 or 25GBase-LR',
                                                   0x04: '100GBase-ER4 or 25GBase-ER',
                                                   0x05: '100GBase-SR10',
                                                   0x06: '100G CWDM4',
                                                   0x07: '100G PAM4 Parallel SMF', 
                                                   0x08: '100G ACC or 25GAUI C2M ACC',
                                                   0x09: 'obsolete',
                                                   0x0a: 'reserved',
                                                   0x0b: '100GBase-CR4 or 25GBase-CR CA-L',
                                                   0x0d: '25GBase-CR CA-N',
                                                   0x0f: 'reserved',
                                                   0x10: '40GBase-ER4',
                                                   0x11: '4x10GBase-SR',
                                                   0x12: '40G PSM4 Parallel SMF',
                                                   0x13: 'G959.1 profile P1I1-2D1 (10709 MBd, 2km, 1310nm SM)',
                                                   0x15: 'G959.1 profile P1S1-2D2 (10709 MBd, 40km, 1550nm SM)',
                                                   0x15: 'G959.1 profile P1L1-2D2 (10709 MBd, 80km, 1550nm SM)',
                                                   0x16: '10GBase-T with SFI electrical interface',
                                                   0x17: '100G CLR4',
                                                   0x18: '100G AOC or 25GAUI C2M AOC. Providing worst BER of 10^(-12) or below',
                                                   0x19: '100G ACC or 25GAUI C2M ACC. Providing worst BER of 10^(-12) or below',
                                                   0x1a: '100GE-DWDM2 (DWDM transceiver using 2 wavelengths on a 1550nm DWDM grid)',
                                                   0x1b: '100G 1550nm WDM (4 wavelengths)',
                                                   0x1c: '10GBase-T short reach (30 meters)',
                                                   0x1d: '5GBase-T',
                                                   0x1e: '2.5Gbase-T',
                                                   0x1f: '40G SWDM4',
                                                   0x20: '100G SWDM4',
                                                   0x21: '100G PAM4 Bidi',
                                                   0x22: '4WDM-10 MSA (10km version of 100G CWDM4 same RS(528, 514) FEC in host system)',
                                                   0x23: '4WDM-20 MdA (20km version of 100GBase-LR4 with RS(528, 514) FEC in host system)',
                                                   0x24: '4WDM-40 MSA (40km reach with APD receiver and RS(528, 514) FEC in host system)',
                                                   0xff: 'reserved'}

